url: 'https://piscespieces.github.io'
baseurl: '/'
title: 'Conversalo'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
