url: 'https://conversalo.ai'
baseurl: '/'
title: 'Conversalo'
site: "Conversalo"
description: "Conversalo es un chatbot de terapia IA en WhatsApp, especializado en Terapia Cognitivo Conductual (TCC), que ofrece apoyo emocional y psicológico gratuito, confidencial y siempre disponible."
image: "/assets/images/opengraph.png"

plugins:
  - jekyll-postcss
  - jekyll-sitemap

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
